### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by LordBilbon** [WDaan/hoppscotch-helm#12]
Hello, thank you for your work but I can't install your chart, I have several issues.
If I install it with `helm install hoppscotch hoppscotch/hoppscotch -f values.yaml` the global.env are not taken: 

```
coalesce.go:223 : warning : destination for hoppscotch.admin.env is a table. Ignore values that are not tables ([])
coalesce.go:223 : warning: destination for hoppscotch.backend.env is a table. Ignore non-table value ([])
coalesce.go:223 : warning : destination for hoppscotch.web.env is a table. Ignore non-table value ([])
```

I also have a issue with ingress:
`Error: template: hoppscotch/templates/web/ingress.yaml:3:23: executing "hoppscotch/templates/web/ingress.yaml" at <.Values.service.httpPort>: nil pointer evaluating interface {}.httpPort"`

I cloned your repo, and the global.env works, but the containers are in crashloopbackoff 
`standard_init_linux.go:228: exec user process caused: operation not permitted` and same issue with ingress.

I doesn't understand why, thanks for your help.

**Comment by WDaan** [comment]
This chart is unfortunately not ready to be used yet, at all. Still tons of things that needed to be figured out. I fired this up as a starting point, hoping it would get picked up by the official team, but unfortunately haven't gotten any traction yet.

**Comment by jasonyop** [comment]
Hi, I currently working with your work to host hoppscotch in k8s, however i got error when install for admin and web i get   operation not permitted error. 

For backend,  
````
Fri, 10 May 2024 10:04:40 GMT express-session deprecated undefined resave option; provide resave option at dist/main.js:15:13                                                                                   ││ Fri, 10 May 2024 10:04:40 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at dist/main.js:15:13                                                             ││ Enabling CORS with production settings                                                                                                                                                                          ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RoutesResolver] AuthController {/auth} (version: 1): +14ms                                                                                                        ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/signin, POST} (version: 1) route +6ms                                                                                               ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/verify, POST} (version: 1) route +1ms                                                                                               ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/refresh, GET} (version: 1) route +1ms                                                                                               ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/google, GET} (version: 1) route +1ms                                                                                                ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/google/callback, GET} (version: 1) route +0ms                                                                                       ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/github, GET} (version: 1) route +1ms                                                                                                ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/github/callback, GET} (version: 1) route +1ms                                                                                       ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/microsoft, GET} (version: 1) route +0ms                                                                                             ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/microsoft/callback, GET} (version: 1) route +1ms                                                                                    ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/logout, GET} (version: 1) route +1ms                                                                                                ││ [Nest] 19  - 05/10/2024, 10:04:40 AM     LOG [RouterExplorer] Mapped {/auth/verify/admin, GET} (version: 1) route +0ms                                                                                          ││ Initialize PubSub                                                                                                                                                                                               ││ [Nest] 19  - 05/10/2024, 10:04:41 AM     LOG [GraphQLModule] Mapped {/graphql, POST} route +560ms                                                                                                               ││ [Nest] 19  - 05/10/2024, 10:04:41 AM     LOG [NestApplication] Nest application successfully started +5ms                                                                                                       ││  ELIFECYCLE  Command failed.
````
I doesn't understand why, quite confuse, thanks for your help.
